# ────────────────────────────────────────────────────────────
# Custom Theme for Hyprlock
# ────────────────────────────────────────────────────────────

$color       = rgba(6, 13, 31, 1.0)     # #060d1f
$inner_color = rgba(6, 13, 31, 1.0)     # Matching background for seamless look
$outer_color = rgba(215, 235, 233, 0.93) # #d7ebe9ee (Border)
$font_color  = rgba(215, 235, 233, 0.93) # #d7ebe9ee (Font)
$check_color = rgba(215, 235, 233, 0.93) # Consistent styling